"""Add incident_type to IncidentReport

Revision ID: 56f138afd185
Revises: 729a998cdb0c
Create Date: 2024-11-21 02:32:48.550966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f138afd185'
down_revision = '729a998cdb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        # Add the incident_type column with a default value
        batch_op.add_column(sa.Column('incident_type', sa.String(), nullable=False, server_default='Unknown'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_column('incident_type')

    # ### end Alembic commands ###