name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/cache@v3
        with:
          path: ./client/dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Deploy to production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: client
          command: pages deploy dist --project-name=ajali
